version: 2.1
orbs:
  dockerro: circleci/docker@1.0.1
jobs:
  build-image:
    executor: dockerro/docker
    steps:
      - setup_remote_docker
      - checkout
      - dockerro/build:
          image: karol71927/ask2020-node-react-cicd
          path: ./server
  test-image:
    docker:
      - image: karol71927/ask2020-node-react-cicd
          path: ./server
    steps:
      - run: npm test
workflows:
  build-and-test:
    jobs:
      - build-image
      - test-image:
          requires:
            - build-image
