version: 2.1
orbs:
  node: circleci/node@2.1.0
jobs:
  docker-setup:
    executor:
      name: node/default
    steps:
      - checkout
      - setup_remote_docker
      
  test-server:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          app-dir: ./server
      - run:
          command: npm test
          working_directory: ./server

  test-client:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          app-dir: ./client
      - run:
          command: npm test
          working_directory: ./client
                    
  docker-publish:
    machine: true
    steps:
      - checkout
      - run: 
          command: | 
            echo \"$DOCKER_PASS\" | docker login -u \"karol71927\" --password-stdin
            sudo docker build -t karol71927/server ./server
            sudo docker push karol71927/server
      - run:
          command: | 
            echo \"$DOCKER_PASS\" | docker login -u \"karol71927\" --password-stdin
            sudo docker build -t karol71927/client ./client
            sudo docker push karol71927/client
                        
workflows:
  build-and-test:
    jobs:
      - docker-setup
      - test-server:
          filters:
            branches:
              only: master
      - test-client:
          filters:
            branches:
              only: master
      - docker-publish:
          filters:
            branches:
              only: master
          requires:
            - docker-setup
            - test-client
            - test-server
          - docker-setup
          - test-server
          - test-client
